import { execFileSync } from "node:child_process";
import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import process from "node:process";

import yaml from "js-yaml";
import ts from "typescript";

const GENERATED_NOTICE =
  "<!-- Generated by npm run context:build. Do not edit by hand. -->";
const require = createRequire(import.meta.url);
const PRETTIER_BIN = require.resolve("prettier/bin/prettier.cjs");
const CODE_EXTENSIONS = new Set([".cjs", ".js", ".mjs", ".ts"]);
const TEXT_CHECK_EXTENSIONS = new Set([".cjs", ".js", ".md", ".mjs", ".ts"]);
const WALK_IGNORES = new Set([
  ".agent-context",
  ".git",
  "coverage",
  "dist",
  "node_modules",
]);

function normalizePath(value) {
  return value.split(path.sep).join("/");
}

function toAbsolutePath(repoRoot, relativePath) {
  return path.resolve(repoRoot, relativePath);
}

function readText(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function ensureDirectory(directoryPath) {
  fs.mkdirSync(directoryPath, { recursive: true });
}

function writeTextIfChanged(filePath, nextContents) {
  const previousContents = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, "utf8")
    : null;

  if (previousContents === nextContents) {
    return false;
  }

  ensureDirectory(path.dirname(filePath));
  fs.writeFileSync(filePath, nextContents);
  return true;
}

function formatGeneratedOutput(repoRoot, relativePath, contents) {
  if (relativePath.endsWith(".mmd")) {
    return contents;
  }

  try {
    return execFileSync(
      process.execPath,
      [PRETTIER_BIN, "--stdin-filepath", relativePath],
      {
        cwd: repoRoot,
        encoding: "utf8",
        input: contents,
      },
    );
  } catch (error) {
    if (
      error instanceof Error &&
      typeof error.message === "string" &&
      error.message.includes("No parser could be inferred")
    ) {
      return contents;
    }

    throw error;
  }
}

function walkDirectory(repoRoot, relativePath, results) {
  const normalizedPath = normalizePath(relativePath);

  if (WALK_IGNORES.has(normalizedPath)) {
    return;
  }

  const absolutePath = toAbsolutePath(repoRoot, relativePath);
  const entries = fs.readdirSync(absolutePath, { withFileTypes: true });

  entries.forEach((entry) => {
    const entryRelativePath =
      normalizedPath === "."
        ? normalizePath(entry.name)
        : normalizePath(path.join(normalizedPath, entry.name));

    if (entry.isDirectory()) {
      walkDirectory(repoRoot, entryRelativePath, results);
      return;
    }

    results.push(entryRelativePath);
  });
}

function collectFilesFromRoot(repoRoot, rootEntry) {
  const normalizedRoot = normalizePath(rootEntry);
  const absoluteRoot = toAbsolutePath(repoRoot, normalizedRoot);

  if (!fs.existsSync(absoluteRoot)) {
    return [];
  }

  if (fs.statSync(absoluteRoot).isFile()) {
    return [normalizedRoot];
  }

  const results = [];
  walkDirectory(repoRoot, normalizedRoot, results);
  return results;
}

function parseYamlFile(filePath) {
  return yaml.load(readText(filePath));
}

function assertArray(value, message) {
  if (!Array.isArray(value)) {
    throw new Error(message);
  }
}

function assertObject(value, message) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(message);
  }
}

function tokenizeText(input) {
  return Array.from(
    new Set(
      input
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, " ")
        .split(/\s+/)
        .filter((token) => token.length >= 3),
    ),
  );
}

export function parseArgs(argv) {
  const flags = new Map();
  const positionals = [];

  argv.forEach((argument) => {
    if (!argument.startsWith("--")) {
      positionals.push(argument);
      return;
    }

    const [rawKey, rawValue] = argument.slice(2).split("=");
    flags.set(rawKey, rawValue === undefined ? "true" : rawValue);
  });

  return {
    flags,
    positionals,
  };
}

function isPathInGeneratedRoots(relativePath, subsystemIndex) {
  return subsystemIndex.generated_roots.some((pattern) =>
    path.posix.matchesGlob(relativePath, `${normalizePath(pattern)}/**`),
  );
}

function isPathExplicitlyExempt(relativePath, subsystemIndex) {
  return subsystemIndex.exempt_paths.includes(relativePath);
}

function validateGlossarySource(glossarySource) {
  assertObject(glossarySource, "glossary/terms.yaml must parse to an object.");
  assertArray(glossarySource.terms, "glossary/terms.yaml must define terms.");
  assertArray(
    glossarySource.examples,
    "glossary/terms.yaml must define examples.",
  );
  assertArray(
    glossarySource.usage_rules,
    "glossary/terms.yaml must define usage_rules.",
  );
  assertArray(
    glossarySource.cross_references,
    "glossary/terms.yaml must define cross_references.",
  );

  const termIds = new Set();

  glossarySource.terms.forEach((term, index) => {
    assertObject(term, `Glossary term ${index + 1} must be an object.`);
    ["id", "canonical", "definition", "kind"].forEach((field) => {
      if (typeof term[field] !== "string" || term[field].trim().length === 0) {
        throw new Error(`Glossary term ${index + 1} is missing ${field}.`);
      }
    });

    if (termIds.has(term.id)) {
      throw new Error(`Glossary term id ${term.id} is duplicated.`);
    }

    termIds.add(term.id);

    assertArray(
      term.discouraged,
      `Glossary term ${term.id} must define discouraged replacements.`,
    );
    assertArray(
      term.applies_to,
      `Glossary term ${term.id} must define applies_to paths.`,
    );
    assertArray(
      term.related_terms,
      `Glossary term ${term.id} must define related_terms.`,
    );
  });

  glossarySource.terms.forEach((term) => {
    term.related_terms.forEach((relatedTermId) => {
      if (!termIds.has(relatedTermId)) {
        throw new Error(
          `Glossary term ${term.id} references unknown related term ${relatedTermId}.`,
        );
      }
    });
  });

  glossarySource.examples.forEach((entry, index) => {
    assertObject(
      entry,
      `Glossary examples entry ${index + 1} must be an object.`,
    );

    if (typeof entry.term !== "string" || entry.term.trim().length === 0) {
      throw new Error(`Glossary examples entry ${index + 1} is missing term.`);
    }

    assertArray(
      entry.examples,
      `Glossary examples entry ${entry.term} must define examples.`,
    );

    if (!termIds.has(entry.term)) {
      throw new Error(
        `Glossary examples entry ${entry.term} references an unknown term.`,
      );
    }
  });

  return glossarySource;
}

function validateSubsystemIndex(subsystemIndex) {
  assertObject(
    subsystemIndex,
    "spec/subsystems/index.yaml must parse to an object.",
  );

  [
    "source_roots",
    "generated_roots",
    "exempt_paths",
    "architecture_rules",
  ].forEach((field) => {
    assertArray(
      subsystemIndex[field],
      `spec/subsystems/index.yaml must define ${field}.`,
    );
  });

  return subsystemIndex;
}

function validateSubsystemRecord(record, filePath) {
  assertObject(record, `${filePath} must parse to an object.`);

  ["id", "title", "status", "summary"].forEach((field) => {
    if (
      typeof record[field] !== "string" ||
      record[field].trim().length === 0
    ) {
      throw new Error(`${filePath} is missing ${field}.`);
    }
  });

  [
    "owned_paths",
    "related_paths",
    "depends_on",
    "used_by",
    "glossary_terms",
    "tests",
    "decision_refs",
  ].forEach((field) => {
    assertArray(record[field], `${filePath} must define ${field}.`);
  });

  [
    "entrypoints",
    "public_contracts",
    "invariants",
    "performance_constraints",
  ].forEach((field) => {
    assertArray(record[field], `${filePath} must define ${field}.`);
  });

  assertObject(
    record.required_reads,
    `${filePath} must define required_reads.`,
  );
  assertObject(record.change_policy, `${filePath} must define change_policy.`);
  assertObject(
    record.history_anchors,
    `${filePath} must define history_anchors.`,
  );

  return record;
}

function parseFrontmatter(filePath) {
  const contents = readText(filePath);
  const match = contents.match(/^---\n([\s\S]*?)\n---\n/);

  if (!match) {
    throw new Error(`${filePath} is missing YAML frontmatter.`);
  }

  return {
    body: contents.slice(match[0].length),
    frontmatter: yaml.load(match[1]),
  };
}

function loadGlossarySource(repoRoot) {
  return validateGlossarySource(
    parseYamlFile(toAbsolutePath(repoRoot, "glossary/terms.yaml")),
  );
}

function loadSubsystemIndex(repoRoot) {
  return validateSubsystemIndex(
    parseYamlFile(toAbsolutePath(repoRoot, "spec/subsystems/index.yaml")),
  );
}

function loadSubsystemRecords(repoRoot) {
  const subsystemDirectory = toAbsolutePath(repoRoot, "spec/subsystems");
  const entries = fs
    .readdirSync(subsystemDirectory)
    .filter((entry) => entry.endsWith(".yaml") && entry !== "index.yaml")
    .sort();

  const records = entries.map((entry) => {
    const relativePath = normalizePath(path.join("spec/subsystems", entry));
    const parsed = validateSubsystemRecord(
      parseYamlFile(toAbsolutePath(repoRoot, relativePath)),
      relativePath,
    );

    return {
      ...parsed,
      filePath: relativePath,
    };
  });

  const ids = new Set(records.map((record) => record.id));

  records.forEach((record) => {
    [...record.depends_on, ...record.used_by].forEach((dependencyId) => {
      if (!ids.has(dependencyId)) {
        throw new Error(
          `${record.filePath} references unknown subsystem ${dependencyId}.`,
        );
      }
    });
  });

  return records;
}

function loadAdrRecords(repoRoot) {
  const adrDirectory = toAbsolutePath(repoRoot, "spec/decisions");
  const entries = fs
    .readdirSync(adrDirectory)
    .filter((entry) => entry.endsWith(".md"))
    .sort();

  return entries.map((entry) => {
    const relativePath = normalizePath(path.join("spec/decisions", entry));
    const parsed = parseFrontmatter(toAbsolutePath(repoRoot, relativePath));

    return {
      ...parsed.frontmatter,
      body: parsed.body,
      filePath: relativePath,
    };
  });
}

export function loadContextData(repoRoot = process.cwd()) {
  const glossary = loadGlossarySource(repoRoot);
  const subsystemIndex = loadSubsystemIndex(repoRoot);
  const subsystems = loadSubsystemRecords(repoRoot);
  const adrs = loadAdrRecords(repoRoot);

  return {
    adrs,
    glossary,
    repoRoot,
    subsystemIndex,
    subsystems,
  };
}

function renderGlossaryTerm(term, glossarySource) {
  const discouragedLines = term.discouraged.length
    ? term.discouraged.map((entry) => `  - ${entry}`).join("\n")
    : "  - none";
  const appliesToLines = term.applies_to
    .map((entry) => `  - \`${entry}\``)
    .join("\n");
  const canonicalTerms = new Map(
    glossarySource.terms.map((entry) => [entry.id, entry.canonical]),
  );
  const relatedTerms = term.related_terms
    .map((entry) => `\`${canonicalTerms.get(entry) || entry}\``)
    .join(", ");

  return [
    `\`${term.canonical}\``,
    "",
    `- ${term.definition}`,
    `- Kind: \`${term.kind}\``,
    "- Discouraged replacements:",
    discouragedLines,
    "- Applies to:",
    appliesToLines,
    `- Related terms: ${relatedTerms || "none"}`,
    "",
  ].join("\n");
}

export function generateGlossaryReadme(glossarySource) {
  const exampleRows = glossarySource.examples
    .map((entry) => {
      const term = glossarySource.terms.find(
        (termEntry) => termEntry.id === entry.term,
      );
      const exampleList = entry.examples
        .map((example) => `\`${example}\``)
        .join(", ");

      return `| ${term && term.canonical ? term.canonical : entry.term} | ${exampleList} |`;
    })
    .join("\n");
  const usageRules = glossarySource.usage_rules
    .map((rule) => `- ${rule}`)
    .join("\n");
  const crossReferences = glossarySource.cross_references
    .map((reference) => `- \`${reference}\``)
    .join("\n");

  return [
    GENERATED_NOTICE,
    "# Project glossary",
    "",
    "This directory is the authoritative source for project nomenclature. `../spec/README.md` defines implemented behavior. This glossary defines the exact words the project uses when describing that behavior.",
    "",
    "When code, docs, comments, and spec text refer to the same concept, they should use the glossary term directly unless an implementation-detail name is intentionally narrower.",
    "",
    "## Core Terms",
    "",
    ...glossarySource.terms.flatMap((term) => [
      renderGlossaryTerm(term, glossarySource),
    ]),
    "## Examples",
    "",
    "| Term | Example files or surfaces |",
    "| ---- | ------------------------ |",
    exampleRows,
    "",
    "## Usage Rules",
    "",
    usageRules,
    "",
    "## Cross References",
    "",
    crossReferences,
    "",
  ].join("\n");
}

function isCodeFile(relativePath) {
  return CODE_EXTENSIONS.has(path.extname(relativePath));
}

function isTextCheckFile(relativePath) {
  return TEXT_CHECK_EXTENSIONS.has(path.extname(relativePath));
}

function resolveImportSpecifier(repoRoot, fromFile, rawSpecifier) {
  if (
    !rawSpecifier ||
    (!rawSpecifier.startsWith("./") && !rawSpecifier.startsWith("../"))
  ) {
    return null;
  }

  const fromDirectory = path.dirname(fromFile);
  const resolvedBase = normalizePath(path.join(fromDirectory, rawSpecifier));
  const candidatePaths = [];

  const extension = path.extname(resolvedBase);
  if (extension) {
    if (extension === ".js") {
      candidatePaths.push(resolvedBase.replace(/\.js$/, ".ts"));
      candidatePaths.push(resolvedBase.replace(/\.js$/, ".mjs"));
    }
    candidatePaths.push(resolvedBase);
  } else {
    [".ts", ".js", ".mjs"].forEach((suffix) => {
      candidatePaths.push(`${resolvedBase}${suffix}`);
    });
    ["index.ts", "index.js", "index.mjs"].forEach((suffix) => {
      candidatePaths.push(normalizePath(path.join(resolvedBase, suffix)));
    });
  }

  const resolvedPath = candidatePaths.find((candidatePath) =>
    fs.existsSync(toAbsolutePath(repoRoot, candidatePath)),
  );

  return resolvedPath ? normalizePath(resolvedPath) : null;
}

function collectSourceImports(repoRoot, filePath, sourceText) {
  const sourceFile = ts.createSourceFile(
    filePath,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    filePath.endsWith(".ts") ? ts.ScriptKind.TS : ts.ScriptKind.JS,
  );
  const imports = new Set();

  function maybeAddSpecifier(specifierText) {
    if (typeof specifierText !== "string") {
      return;
    }

    const resolved = resolveImportSpecifier(repoRoot, filePath, specifierText);
    if (resolved) {
      imports.add(resolved);
    }
  }

  function visit(node) {
    if (
      (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
      node.moduleSpecifier &&
      ts.isStringLiteral(node.moduleSpecifier)
    ) {
      maybeAddSpecifier(node.moduleSpecifier.text);
    }

    if (
      ts.isCallExpression(node) &&
      node.expression.kind === ts.SyntaxKind.ImportKeyword &&
      node.arguments.length === 1 &&
      ts.isStringLiteral(node.arguments[0])
    ) {
      maybeAddSpecifier(node.arguments[0].text);
    }

    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return [...imports].sort();
}

function collectFirstPartyFiles(repoRoot, subsystemIndex) {
  const files = subsystemIndex.source_roots.flatMap((rootEntry) =>
    collectFilesFromRoot(repoRoot, rootEntry),
  );
  const uniqueFiles = Array.from(new Set(files)).sort();

  return uniqueFiles.filter((relativePath) => {
    if (isPathExplicitlyExempt(relativePath, subsystemIndex)) {
      return false;
    }

    return !isPathInGeneratedRoots(relativePath, subsystemIndex);
  });
}

function matchPatterns(relativePath, patterns) {
  return patterns.some((pattern) =>
    path.posix.matchesGlob(relativePath, normalizePath(pattern)),
  );
}

function getOwningSubsystems(relativePath, subsystems) {
  return subsystems.filter((subsystem) =>
    matchPatterns(relativePath, subsystem.owned_paths),
  );
}

function getCoveredSubsystems(relativePath, subsystems) {
  return subsystems.filter(
    (subsystem) =>
      matchPatterns(relativePath, subsystem.owned_paths) ||
      matchPatterns(relativePath, subsystem.related_paths),
  );
}

export function buildRepoMap(contextData) {
  const firstPartyFiles = collectFirstPartyFiles(
    contextData.repoRoot,
    contextData.subsystemIndex,
  );
  const codeFiles = firstPartyFiles.filter(isCodeFile);
  const importsByFile = new Map();
  const dependentsByFile = new Map();

  codeFiles.forEach((relativePath) => {
    const absolutePath = toAbsolutePath(contextData.repoRoot, relativePath);
    const imports = collectSourceImports(
      contextData.repoRoot,
      relativePath,
      readText(absolutePath),
    );
    importsByFile.set(relativePath, imports);
    imports.forEach((importPath) => {
      const dependents = dependentsByFile.get(importPath) || [];
      dependents.push(relativePath);
      dependentsByFile.set(importPath, dependents);
    });
  });

  return {
    generatedBy: "npm run context:build",
    version: 1,
    files: firstPartyFiles.map((relativePath) => ({
      dependents: [...new Set(dependentsByFile.get(relativePath) || [])].sort(),
      imports: importsByFile.get(relativePath) || [],
      owners: getOwningSubsystems(relativePath, contextData.subsystems).map(
        (subsystem) => subsystem.id,
      ),
      path: relativePath,
      type: isCodeFile(relativePath) ? "code" : "text",
    })),
    subsystems: contextData.subsystems.map((subsystem) => ({
      depends_on: subsystem.depends_on,
      id: subsystem.id,
      owned_paths: subsystem.owned_paths,
      related_paths: subsystem.related_paths,
      status: subsystem.status,
      used_by: subsystem.used_by,
    })),
  };
}

export function renderSubsystemGraph(contextData) {
  const lines = [GENERATED_NOTICE, "flowchart TD"];

  contextData.subsystems.forEach((subsystem) => {
    lines.push(
      `  ${subsystem.id.replace(/-/g, "_")}["${subsystem.title} (${subsystem.status})"]`,
    );
  });

  contextData.subsystems.forEach((subsystem) => {
    subsystem.depends_on.forEach((dependencyId) => {
      lines.push(
        `  ${subsystem.id.replace(/-/g, "_")} --> ${dependencyId.replace(
          /-/g,
          "_",
        )}`,
      );
    });
  });

  return `${lines.join("\n")}\n`;
}

function uniqueSorted(values) {
  return [...new Set(values)].sort();
}

function scoreSubsystem(subsystem, glossarySource, taskText, taskTokens) {
  const loweredTaskText = taskText.toLowerCase();
  let score = 0;
  const reasons = [];
  const searchableStrings = [
    subsystem.id,
    subsystem.title,
    subsystem.summary,
    ...subsystem.public_contracts.map((entry) => entry.name),
    ...subsystem.invariants.map((entry) => entry.statement),
    ...subsystem.performance_constraints,
    ...subsystem.glossary_terms,
  ]
    .join(" \n ")
    .toLowerCase();

  taskTokens.forEach((token) => {
    if (subsystem.id.toLowerCase().includes(token)) {
      score += 4;
      reasons.push(`id:${token}`);
      return;
    }

    if (subsystem.title.toLowerCase().includes(token)) {
      score += 4;
      reasons.push(`title:${token}`);
      return;
    }

    if (searchableStrings.includes(token)) {
      score += 1;
      reasons.push(`text:${token}`);
    }
  });

  glossarySource.terms.forEach((term) => {
    if (!subsystem.glossary_terms.includes(term.canonical)) {
      return;
    }

    if (loweredTaskText.includes(term.canonical.toLowerCase())) {
      score += 5;
      reasons.push(`glossary:${term.canonical}`);
      return;
    }

    if (
      term.discouraged.some((entry) =>
        loweredTaskText.includes(entry.toLowerCase()),
      )
    ) {
      score += 3;
      reasons.push(`glossary-discouraged:${term.canonical}`);
    }
  });

  return {
    reasons: uniqueSorted(reasons),
    score,
    subsystem,
  };
}

function expandSubsystemSelection(scoredSubsystems, allSubsystems) {
  const selectedIds = new Set(
    scoredSubsystems
      .filter((entry) => entry.score > 0)
      .map((entry) => entry.subsystem.id),
  );
  const expandedIds = new Set(selectedIds);

  allSubsystems.forEach((subsystem) => {
    if (!selectedIds.has(subsystem.id)) {
      return;
    }

    subsystem.depends_on.forEach((dependencyId) =>
      expandedIds.add(dependencyId),
    );
    subsystem.used_by.forEach((dependencyId) => expandedIds.add(dependencyId));
  });

  const governanceSubsystem = allSubsystems.find(
    (subsystem) => subsystem.id === "repo-governance-context-system",
  );

  if (governanceSubsystem && expandedIds.size > 0) {
    expandedIds.add(governanceSubsystem.id);
  }

  return {
    expandedIds: [...expandedIds],
    selectedIds: [...selectedIds],
  };
}

function determineTaskConfidence(scoredSubsystems, selectedIds) {
  if (!selectedIds.length) {
    return "low";
  }

  const positiveScores = scoredSubsystems.filter((entry) => entry.score > 0);
  const topScore = positiveScores[0] ? positiveScores[0].score : 0;
  const secondScore = positiveScores[1] ? positiveScores[1].score : 0;

  if (topScore >= 6 && topScore > secondScore) {
    return "high";
  }

  return "medium";
}

export function buildTaskPacket(contextData, options) {
  const task = options.task.trim();

  if (!task.length) {
    throw new Error("A non-empty task description is required.");
  }

  const taskTokens = tokenizeText(task);
  const scoredSubsystems = contextData.subsystems
    .map((subsystem) =>
      scoreSubsystem(subsystem, contextData.glossary, task, taskTokens),
    )
    .sort(
      (left, right) =>
        right.score - left.score ||
        left.subsystem.id.localeCompare(right.subsystem.id),
    );
  const { expandedIds, selectedIds } = expandSubsystemSelection(
    scoredSubsystems,
    contextData.subsystems,
  );
  const selectedSubsystems = contextData.subsystems.filter((subsystem) =>
    expandedIds.includes(subsystem.id),
  );
  const lockedSubsystems = selectedSubsystems
    .filter((subsystem) => subsystem.status === "locked")
    .map((subsystem) => subsystem.id);
  const allowLocked = uniqueSorted(
    (options.allowLocked || []).filter((entry) =>
      lockedSubsystems.includes(entry),
    ),
  );
  const requiredSpecReads = uniqueSorted([
    "spec/README.md",
    ...selectedSubsystems.flatMap((subsystem) => subsystem.required_reads.spec),
  ]);
  const requiredDocsReads = uniqueSorted(
    selectedSubsystems.flatMap((subsystem) => subsystem.required_reads.docs),
  );
  const requiredDecisionReads = uniqueSorted(
    selectedSubsystems.flatMap(
      (subsystem) => subsystem.required_reads.decisions,
    ),
  );
  const requiredTests = uniqueSorted(
    selectedSubsystems.flatMap((subsystem) => subsystem.tests),
  );
  const glossaryTerms = uniqueSorted(
    selectedSubsystems.flatMap((subsystem) => subsystem.glossary_terms),
  );

  return {
    allowLocked,
    confidence: determineTaskConfidence(scoredSubsystems, selectedIds),
    createdAt: "local",
    glossaryTerms,
    lockedSubsystems,
    matchedSubsystems: scoredSubsystems
      .filter((entry) => entry.score > 0)
      .map((entry) => ({
        id: entry.subsystem.id,
        reasons: entry.reasons,
        score: entry.score,
        status: entry.subsystem.status,
      })),
    requiredDecisionReads,
    requiredDocsReads,
    requiredSpecReads,
    requiredSubsystemRecords: selectedSubsystems.map(
      (subsystem) => subsystem.filePath,
    ),
    requiredTests,
    selectedSubsystemIds: selectedIds,
    task,
    touchedSubsystemIds: selectedSubsystems.map((subsystem) => subsystem.id),
  };
}

export function renderTaskMarkdown(taskPacket) {
  const lines = [
    "# Active Task Brief",
    "",
    `Task: ${taskPacket.task}`,
    `Confidence: ${taskPacket.confidence}`,
    "",
    "## Matched Subsystems",
    "",
  ];

  taskPacket.matchedSubsystems.forEach((entry) => {
    lines.push(
      `- ${entry.id} (${entry.status}, score ${entry.score}): ${entry.reasons.join(", ")}`,
    );
  });

  lines.push("", "## Required Reads", "");
  taskPacket.requiredSpecReads.forEach((entry) => {
    lines.push(`- ${entry}`);
  });
  taskPacket.requiredDocsReads.forEach((entry) => {
    lines.push(`- ${entry}`);
  });
  taskPacket.requiredDecisionReads.forEach((entry) => {
    lines.push(`- ${entry}`);
  });
  lines.push("", "## Locked Subsystems", "");
  if (taskPacket.lockedSubsystems.length === 0) {
    lines.push("- none");
  } else {
    taskPacket.lockedSubsystems.forEach((entry) => {
      const allowedLabel = taskPacket.allowLocked.includes(entry)
        ? "allowed"
        : "not allowed";
      lines.push(`- ${entry}: ${allowedLabel}`);
    });
  }
  lines.push("", "## Required Tests", "");
  taskPacket.requiredTests.forEach((entry) => {
    lines.push(`- ${entry}`);
  });
  lines.push("", "## Glossary Terms", "");
  if (taskPacket.glossaryTerms.length === 0) {
    lines.push("- none");
  } else {
    taskPacket.glossaryTerms.forEach((entry) => {
      lines.push(`- ${entry}`);
    });
  }

  return `${lines.join("\n")}\n`;
}

function getGitStatus(repoRoot) {
  const output = execFileSync(
    "git",
    ["status", "--short", "--untracked-files=all"],
    {
      cwd: repoRoot,
      encoding: "utf8",
    },
  );

  return output
    .split("\n")
    .map((line) => line.trimEnd())
    .filter(Boolean)
    .map((line) => line.slice(3));
}

function readActiveTask(repoRoot, subsystemIndex) {
  const taskPath = toAbsolutePath(repoRoot, subsystemIndex.task_state_path);

  if (!fs.existsSync(taskPath)) {
    return null;
  }

  return JSON.parse(readText(taskPath));
}

function assertOwnedCoverage(contextData, repoMap) {
  const unmappedFiles = repoMap.files
    .filter((file) => file.owners.length === 0)
    .map((file) => file.path);

  if (unmappedFiles.length) {
    throw new Error(
      `Unmapped first-party files detected:\n${unmappedFiles
        .map((entry) => `- ${entry}`)
        .join("\n")}`,
    );
  }
}

function expectedGeneratedFiles(contextData) {
  const repoMap = buildRepoMap(contextData);

  return {
    "glossary/README.md": formatGeneratedOutput(
      contextData.repoRoot,
      "glossary/README.md",
      generateGlossaryReadme(contextData.glossary),
    ),
    "spec/generated/repo-map.json": formatGeneratedOutput(
      contextData.repoRoot,
      "spec/generated/repo-map.json",
      `${JSON.stringify(repoMap, null, 2)}\n`,
    ),
    "spec/generated/subsystem-graph.mmd": formatGeneratedOutput(
      contextData.repoRoot,
      "spec/generated/subsystem-graph.mmd",
      renderSubsystemGraph(contextData),
    ),
  };
}

export function buildContextArtifacts(contextData) {
  const repoMap = buildRepoMap(contextData);
  assertOwnedCoverage(contextData, repoMap);
  return expectedGeneratedFiles(contextData);
}

export function writeContextArtifacts(contextData) {
  const outputs = buildContextArtifacts(contextData);
  const changedFiles = [];

  Object.entries(outputs).forEach(([relativePath, contents]) => {
    const didChange = writeTextIfChanged(
      toAbsolutePath(contextData.repoRoot, relativePath),
      contents,
    );
    if (didChange) {
      changedFiles.push(relativePath);
    }
  });

  return changedFiles;
}

function diffGeneratedArtifacts(contextData) {
  const outputs = buildContextArtifacts(contextData);

  return Object.entries(outputs)
    .filter(([relativePath, contents]) => {
      const absolutePath = toAbsolutePath(contextData.repoRoot, relativePath);
      return (
        !fs.existsSync(absolutePath) || readText(absolutePath) !== contents
      );
    })
    .map(([relativePath]) => relativePath);
}

function touchedSubsystemsForFiles(filePaths, subsystems) {
  return uniqueSorted(
    filePaths.flatMap((filePath) =>
      getCoveredSubsystems(filePath, subsystems).map(
        (subsystem) => subsystem.id,
      ),
    ),
  );
}

function changedFilesNeedingSubsystemRecord(filePaths) {
  return filePaths.filter(
    (filePath) =>
      filePath.startsWith("src/") ||
      filePath.startsWith("scripts/") ||
      [
        ".gitignore",
        ".nvmrc",
        "AGENTS.md",
        "README.md",
        "eslint.config.mjs",
        "package-lock.json",
        "package.json",
        "tsconfig.build.json",
        "tsconfig.json",
        "vitest.config.ts",
      ].includes(filePath),
  );
}

function checkTaskCoverage(contextData, activeTask, changedFiles) {
  const changedSubsystems = touchedSubsystemsForFiles(
    changedFiles,
    contextData.subsystems,
  );
  const unexpectedSubsystems = changedSubsystems.filter(
    (subsystemId) => !activeTask.touchedSubsystemIds.includes(subsystemId),
  );

  if (unexpectedSubsystems.length) {
    throw new Error(
      `Changed files spill outside the active task packet:\n${unexpectedSubsystems
        .map((entry) => `- ${entry}`)
        .join("\n")}`,
    );
  }

  const disallowedLocked = changedSubsystems.filter((subsystemId) => {
    const subsystem = contextData.subsystems.find(
      (entry) => entry.id === subsystemId,
    );

    return (
      subsystem &&
      subsystem.status === "locked" &&
      !activeTask.allowLocked.includes(subsystemId)
    );
  });

  if (disallowedLocked.length) {
    throw new Error(
      `Locked subsystem edits require explicit allow-list entries:\n${disallowedLocked
        .map((entry) => `- ${entry}`)
        .join("\n")}`,
    );
  }

  const changedSubsystemRecords = new Set(
    changedFiles.filter((filePath) => filePath.startsWith("spec/subsystems/")),
  );
  const changedDecisions = changedFiles.filter((filePath) =>
    filePath.startsWith("spec/decisions/"),
  );
  const touchedOwnedSubsystemIds = touchedSubsystemsForFiles(
    changedFilesNeedingSubsystemRecord(changedFiles),
    contextData.subsystems,
  );

  touchedOwnedSubsystemIds.forEach((subsystemId) => {
    const subsystem = contextData.subsystems.find(
      (entry) => entry.id === subsystemId,
    );

    if (!subsystem) {
      return;
    }

    if (!changedSubsystemRecords.has(subsystem.filePath)) {
      throw new Error(
        `Touched subsystem ${subsystemId} requires updating ${subsystem.filePath}.`,
      );
    }

    if (subsystem.status === "locked" && changedDecisions.length === 0) {
      throw new Error(
        `Touched locked subsystem ${subsystemId} requires an ADR change under spec/decisions/.`,
      );
    }
  });
}

export function checkContextState(contextData) {
  const staleArtifacts = diffGeneratedArtifacts(contextData);

  if (staleArtifacts.length) {
    throw new Error(
      `Derived context artifacts are stale. Run npm run context:build.\n${staleArtifacts
        .map((entry) => `- ${entry}`)
        .join("\n")}`,
    );
  }

  const changedFiles = getGitStatus(contextData.repoRoot).filter(
    (relativePath) => {
      if (relativePath.startsWith(".agent-context/")) {
        return false;
      }

      if (
        contextData.subsystemIndex.generated_roots.some((rootPath) =>
          path.posix.matchesGlob(relativePath, `${normalizePath(rootPath)}/**`),
        )
      ) {
        return false;
      }

      return true;
    },
  );

  if (!changedFiles.length) {
    return;
  }

  const activeTask = readActiveTask(
    contextData.repoRoot,
    contextData.subsystemIndex,
  );

  if (!activeTask) {
    throw new Error(
      'Changed files detected without .agent-context/active-task.json. Run npm run context:task -- "<task>" first.',
    );
  }

  checkTaskCoverage(contextData, activeTask, changedFiles);
}

export function checkTerminology(contextData) {
  const filesToScan = collectFirstPartyFiles(
    contextData.repoRoot,
    contextData.subsystemIndex,
  ).filter(
    (relativePath) =>
      isTextCheckFile(relativePath) && relativePath !== "glossary/terms.yaml",
  );
  const findings = [];

  filesToScan.forEach((relativePath) => {
    const contents = readText(
      toAbsolutePath(contextData.repoRoot, relativePath),
    );

    if (contents.startsWith(GENERATED_NOTICE)) {
      return;
    }

    const loweredContents = contents.toLowerCase();

    contextData.glossary.terms.forEach((term) => {
      term.discouraged.forEach((discouragedValue) => {
        if (loweredContents.includes(discouragedValue.toLowerCase())) {
          findings.push(
            `${relativePath}: discouraged term "${discouragedValue}" should be replaced with "${term.canonical}".`,
          );
        }
      });
    });
  });

  if (findings.length) {
    throw new Error(findings.join("\n"));
  }
}

export function checkArchitecture(contextData) {
  const repoMap = buildRepoMap(contextData);
  const findings = [];

  contextData.subsystemIndex.architecture_rules.forEach((rule) => {
    repoMap.files
      .filter(
        (file) =>
          file.type === "code" &&
          rule.from.some((pattern) =>
            path.posix.matchesGlob(file.path, normalizePath(pattern)),
          ),
      )
      .forEach((file) => {
        file.imports.forEach((importPath) => {
          const isForbidden = rule.forbidden.some((pattern) =>
            path.posix.matchesGlob(importPath, normalizePath(pattern)),
          );
          const isAllowed = (rule.allowed || []).some((pattern) =>
            path.posix.matchesGlob(importPath, normalizePath(pattern)),
          );
          const isExcepted = (rule.exceptions || []).some(
            (exception) =>
              path.posix.matchesGlob(
                file.path,
                normalizePath(exception.from),
              ) &&
              path.posix.matchesGlob(importPath, normalizePath(exception.to)),
          );

          if (isForbidden && !isAllowed && !isExcepted) {
            findings.push(
              `${rule.id}: ${file.path} -> ${importPath}\n  ${rule.message}`,
            );
          }
        });
      });
  });

  if (findings.length) {
    throw new Error(findings.join("\n"));
  }
}

export function writeActiveTask(contextData, taskPacket) {
  const taskJsonPath = toAbsolutePath(
    contextData.repoRoot,
    contextData.subsystemIndex.task_state_path,
  );
  const taskMarkdownPath = toAbsolutePath(
    contextData.repoRoot,
    contextData.subsystemIndex.task_markdown_path,
  );

  writeTextIfChanged(taskJsonPath, `${JSON.stringify(taskPacket, null, 2)}\n`);
  writeTextIfChanged(taskMarkdownPath, renderTaskMarkdown(taskPacket));
}

export function buildReviewPacket(contextData) {
  const activeTask = readActiveTask(
    contextData.repoRoot,
    contextData.subsystemIndex,
  );

  if (!activeTask) {
    throw new Error(
      "Cannot build a review packet without .agent-context/active-task.json. Run npm run context:task first.",
    );
  }

  const changedFiles = getGitStatus(contextData.repoRoot).filter(
    (relativePath) => !relativePath.startsWith(".agent-context/"),
  );
  const touchedSubsystems = touchedSubsystemsForFiles(
    changedFiles,
    contextData.subsystems,
  )
    .map((subsystemId) =>
      contextData.subsystems.find((subsystem) => subsystem.id === subsystemId),
    )
    .filter(Boolean);
  const changedAuthorityFiles = changedFiles.filter(
    (filePath) =>
      filePath.startsWith("spec/") ||
      filePath.startsWith("docs/") ||
      filePath.startsWith("glossary/") ||
      filePath === "README.md" ||
      filePath === "AGENTS.md",
  );

  const lines = [
    "# Drift Review Packet",
    "",
    `Task: ${activeTask.task}`,
    `Confidence: ${activeTask.confidence}`,
    "",
    "## Changed Files",
    "",
    ...changedFiles.map((entry) => `- ${entry}`),
    "",
    "## Touched Subsystems",
    "",
    ...touchedSubsystems.flatMap((subsystem) => [
      `- ${subsystem.id} (${subsystem.status})`,
      ...subsystem.invariants.map(
        (invariant) => `  - ${invariant.id}: ${invariant.statement}`,
      ),
    ]),
    "",
    "## Changed Authoritative Artifacts",
    "",
    ...changedAuthorityFiles.map((entry) => `- ${entry}`),
    "",
  ];

  return `${lines.join("\n")}\n`;
}

export function writeReviewPacket(contextData, reviewPacket) {
  writeTextIfChanged(
    toAbsolutePath(
      contextData.repoRoot,
      contextData.subsystemIndex.review_packet_path,
    ),
    reviewPacket,
  );
}

export function formatBuildSummary(changedFiles) {
  if (!changedFiles.length) {
    return "Context artifacts already up to date.";
  }

  return `Updated context artifacts:\n${changedFiles
    .map((entry) => `- ${entry}`)
    .join("\n")}`;
}

export function formatTaskSummary(taskPacket) {
  return renderTaskMarkdown(taskPacket).trimEnd();
}

export function formatReviewSummary(reviewPacket) {
  return reviewPacket.trimEnd();
}
